// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using school_management_service.src.Infrastructure.Data;

#nullable disable

namespace school_management_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExtracurricularActivityStudent", b =>
                {
                    b.Property<int>("ExtracurricularActivitiesActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("studentsCitizenId")
                        .HasColumnType("text");

                    b.HasKey("ExtracurricularActivitiesActivityId", "studentsCitizenId");

                    b.HasIndex("studentsCitizenId");

                    b.ToTable("ExtracurricularActivityStudent");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.AcademicRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("integer");

                    b.Property<string>("LetterGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MarksObtained")
                        .HasColumnType("numeric");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("TeacherRemarks")
                        .HasColumnType("text");

                    b.Property<string>("TermSemester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("numeric");

                    b.Property<string>("studentCitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("studentCitizenId");

                    b.ToTable("AcademicRecords");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.AccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataAccessed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequesterOrganization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentCitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("studentCitizenId");

                    b.ToTable("AccessLogs");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarkedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("studentCitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AttendanceId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("studentCitizenId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.BehavioralRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordType")
                        .HasColumnType("integer");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("integer");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("studentCitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("studentCitizenId");

                    b.ToTable("BehavioralRecords");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Cetificate", b =>
                {
                    b.Property<int>("CetificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CetificateId"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CertificateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("DigitalSignature")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentCitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CetificateId");

                    b.HasIndex("studentCitizenId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.ConsentManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConsentExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ConsentGivenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsentToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataCategories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentCitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("studentCitizenId");

                    b.ToTable("ConsentManagements");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.ExtracurricularActivity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("ActivityId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ExtracurricularActivities");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.ParentGuardian", b =>
                {
                    b.Property<int>("GuardianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GuardianId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrimaryContact")
                        .HasColumnType("boolean");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentCitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuardianId");

                    b.HasIndex("studentCitizenId");

                    b.ToTable("ParentGuardians");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.SchoolClass", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassId"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer");

                    b.Property<int>("ClassTeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("GradeLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SchoolClasses");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Student", b =>
                {
                    b.Property<string>("CitizenId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentGradeLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolStudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("schoolClassClassId")
                        .HasColumnType("integer");

                    b.HasKey("CitizenId");

                    b.HasIndex("schoolClassClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.StudentActivity", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnrollmentId"));

                    b.Property<string>("Achievement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AchievementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RolePosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("extracurricularActivityActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("studentCitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("extracurricularActivityActivityId");

                    b.HasIndex("studentCitizenId");

                    b.ToTable("StudentActivities");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.StudentExtracurricular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("extracurricularActivityActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("studentCitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("extracurricularActivityActivityId");

                    b.HasIndex("studentCitizenId");

                    b.ToTable("StudentExtracurriculars");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeacherCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ExtracurricularActivityStudent", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.ExtracurricularActivity", null)
                        .WithMany()
                        .HasForeignKey("ExtracurricularActivitiesActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_service.src.Core.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("studentsCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.AcademicRecord", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.Subject", "subject")
                        .WithMany("AcademicRecords")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_service.src.Core.Entities.Student", "student")
                        .WithMany("AcademicRecords")
                        .HasForeignKey("studentCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.AccessLog", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.Student", "student")
                        .WithMany("AccessLogs")
                        .HasForeignKey("studentCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Attendance", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.Subject", "subject")
                        .WithMany("Attendances")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_service.src.Core.Entities.Student", "student")
                        .WithMany("Attendances")
                        .HasForeignKey("studentCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.BehavioralRecord", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.Teacher", "teacher")
                        .WithMany("BehavioralRecords")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_service.src.Core.Entities.Student", "student")
                        .WithMany("BehavioralRecords")
                        .HasForeignKey("studentCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Cetificate", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.Student", "student")
                        .WithMany("Cetificates")
                        .HasForeignKey("studentCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.ConsentManagement", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.Student", "student")
                        .WithMany("ConsentManagements")
                        .HasForeignKey("studentCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.ExtracurricularActivity", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.Teacher", "teacher")
                        .WithMany("ExtracurricularActivities")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.ParentGuardian", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.Student", "student")
                        .WithMany("ParentGuardians")
                        .HasForeignKey("studentCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.SchoolClass", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.Teacher", "teacher")
                        .WithMany("SchoolClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Student", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.SchoolClass", "schoolClass")
                        .WithMany("Students")
                        .HasForeignKey("schoolClassClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("schoolClass");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.StudentActivity", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.ExtracurricularActivity", "extracurricularActivity")
                        .WithMany("StudentActivities")
                        .HasForeignKey("extracurricularActivityActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_service.src.Core.Entities.Student", "student")
                        .WithMany("StudentActivities")
                        .HasForeignKey("studentCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("extracurricularActivity");

                    b.Navigation("student");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.StudentExtracurricular", b =>
                {
                    b.HasOne("school_management_service.src.Core.Entities.ExtracurricularActivity", "extracurricularActivity")
                        .WithMany()
                        .HasForeignKey("extracurricularActivityActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_service.src.Core.Entities.Student", "student")
                        .WithMany()
                        .HasForeignKey("studentCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("extracurricularActivity");

                    b.Navigation("student");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.ExtracurricularActivity", b =>
                {
                    b.Navigation("StudentActivities");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.SchoolClass", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Student", b =>
                {
                    b.Navigation("AcademicRecords");

                    b.Navigation("AccessLogs");

                    b.Navigation("Attendances");

                    b.Navigation("BehavioralRecords");

                    b.Navigation("Cetificates");

                    b.Navigation("ConsentManagements");

                    b.Navigation("ParentGuardians");

                    b.Navigation("StudentActivities");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Subject", b =>
                {
                    b.Navigation("AcademicRecords");

                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("school_management_service.src.Core.Entities.Teacher", b =>
                {
                    b.Navigation("BehavioralRecords");

                    b.Navigation("ExtracurricularActivities");

                    b.Navigation("SchoolClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
